#!/bin/bash
# Common vars and logic for Backup and Restore WearWare
root="/root/dev"
ww="$root/WearWare"
br="$root/backup-WearWare"

if [ "$#" -gt 2 ]; then
	echo Too many parameters passed
	exit 1
fi

# Process flags
# Only -confirmed is supported
if [[ "${@: -1}" == -* ]]; then
	if [[ "${@: -1}" != "-confirm" ]]; then
		echo "Only -confirm is supported as last argument"
		exit 1
	else
		confirmed=true
	fi
else
	confirmed=false
fi


bf="$1"
bp="$br/$bf"
