#!/bin/bash
# Backs up WearWare

source /usr/local/bin/vars-include

if [ -d "$bp" ]; then
  if [ "$confirmed" != true ]; then
    printf "Need to pass -confirm to overwrite $bf\n\n"
    exit 1
  fi
  printf 'Deleting old folder...\n'
  rm -r "$bp/"*
fi

printf "Backing up WareWare to folder $bf...\n"
if [ ! -d "$bp" ]; then
	mkdir "$bp"
fi
cp -r "$ww/"* "$bp"

printf 'Done.\n\n'